Theme update
ProjectPythia/sphinx-pythia-theme pull request #58
Opened 2024-01-18 17:12 UTC by erogluorhan

FWIW: This is just a draft work in very beginning stage on a potential `sphinx-book-theme` update that includes my local attempts to get things up and running with the followings (which did not succeed yet)

- `sphinx-book-theme>=1.0.0,<1.1.0` (it has the latest version as 1.1.0 but it is not yet supported by `jupyter-book`'s latest version 0.15.1 as of today)
- Python=3.11
- Sphinx=5.0

To get the above things to work with our theme, I also started to update things like directives, but I haven't done much work. 

This branch still has a long way to go to get things to work. 

Please feel free to take whatever you thing would be helpful or ignore.

2024-01-29 21:02 UTC, erogluorhan commented on .github/workflows/ci.yaml
> +      uses: styfle/cancel-workflow-action@0.12.0
Thanks a lot; wasn't aware of this key. Just went over its docs and found it a bit more complicated than what is currently here (e.g. defining groups, specifying if concurrency for PR numbers, etc.), though please feel free to push the change if you'd like that better (and maybe find it more useful than the one here). 

If I were to implement it, should it look something like this:

```
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
```

2024-01-29 21:15 UTC, erogluorhan commented on .github/workflows/ci.yaml
>          run: python setup.py sdist bdist_wheel
Good catch! Even though this existing one should probably keep working, I will look into replacing this with `build` (hadn't use it before). Please feel free to push if you have that close at hand

2024-01-30 04:08 UTC, erogluorhan commented on docs/about.rst
> +.. tab-set-code:: Sphinx
Great catch, removed.

2024-01-30 05:14 UTC, erogluorhan commented on .github/workflows/ci.yaml
>          run: python setup.py sdist bdist_wheel
I think I have incorporated this now. Please have a look

2024-01-30 06:08 UTC, erogluorhan commented
An FYI: The Pythia portal nightly build with this updated theme [built successfully](https://github.com/ProjectPythia/projectpythia.github.io/actions/runs/7706845158/job/21003043090); however, we will need to inspect its [artifact](https://github.com/ProjectPythia/projectpythia.github.io/actions/runs/7706845158/artifacts/1204623717) and maybe perform additional tests to investigate the results of the theme is good for actual deployment.

2024-02-02 00:59 UTC, jukent approved these changes
@erogluorhan This looks pretty reasonable to me and I'm glad that it is working. However it's possible there are things I don't understand well enough to catch. Let me know if you want to do a walk through of the changes. 

Also I'm wondering if there are any lessons you learned while working on this that could go into some internal documentation for ease of future updates.

2024-02-06 19:51 UTC, erogluorhan commented
Hey @jukent , thanks for that! Yes, I can give you a walk through of the current state anytime. Even though I marked this as review-ready, it was more for bringing it to attention of everyone in the loop, and get some feedback/help from the more experienced (since I am not at all experienced on this work). 

The current state of it seems good about that we were able to get Sphinx, theme, and dependency packages up & running with their unpinned versions. However, there is still work to do on getting this new version of the theme to reflect all the features listed [here](https://sphinx-pythia-theme.readthedocs.io/en/latest/about.html). Currently, I am looking into `layout.html` to display the banner page layout, hide the right ToC, etc. in Pythia portal's homepage properly as before.

2024-02-06 21:20 UTC, erogluorhan commented
FYI: [This](https://github.com/ProjectPythia/projectpythia.github.io/actions/runs/7806163431/artifacts/1225049705) is where I am as of now. You can download it and check out `_build/html/index.html` locally.

2024-03-19 15:46 UTC, agoose77 commented on .github/workflows/ci.yaml
> +      uses: styfle/cancel-workflow-action@0.12.0
Sorry, I didn't see this outstanding question. Yes, the concurrency group just needs to be non-unique for the same PR e.g.
```
group: 'docs-${{ github.head_ref || github.run_id }}'
```

This ensures that if the run doesn't have a `head_ref` (non-PRs), then it falls back to a unique identifier.

2024-03-21 22:48 UTC, jukent commented
I am getting an error trying to build the Foundations book because the Cartopy chapter starts with an illegal character. @dcamron do you get a similar error? It might not be related to the theme.

2024-03-22 15:42 UTC, jukent requested changes
<img width="1728" alt="Screenshot 2024-03-22 at 11 26 54 AM" src="https://github.com/ProjectPythia/sphinx-pythia-theme/assets/46687291/191766b5-a9d5-44a0-a625-4a02f60de2b8">

The navbar menu links' color is set to `--pst-color-text-muted`. I think this is too light. On the site now, they're a dark gray that turns teal when hovered over.

The underlining of the link when hovering over it is also new, but I think helpful.

Great work on this! I know it was really a big push.

2024-03-22 17:22 UTC, jukent commented
Steps taken to build.

From Portal or Foundations repository:

`git fetch --all`
`git branch -r`
` git checkout -b theme upstreme/try_updated_theme`
` conda env create -f environment.yml`

Then from the sphinx-pythia-theme repository:

`conda activate pythia-book-dev` (for foundations) or `conda activate pythia` (for portal)
 `pip install -r requirements.txt`
`python -m pip install . --no-deps`

Then in Portal
`cd portal`
`make html`
`open _build/html/index.html`

Or in Foundations
`jupyter-book build .`
open _build/html/index.html`

2024-03-22 22:27 UTC, erogluorhan commented
![image](https://github.com/ProjectPythia/sphinx-pythia-theme/assets/32553057/86f5371f-0477-4fd2-8f2f-3065b2159f31)

How does it look now, @jukent? (screenshot is from my local but I can push it if it is liked)

2024-03-22 22:35 UTC, jukent commented
Yeah that looks great! If you push the commit I'll re-test my build.

2024-03-25 15:22 UTC, jukent approved these changes
Thanks Orhan for all of the hard work that went into this. These changes seem sensible and we've had several chances to look at the Html together. Thanks for updating the CSS to make the foundations navbar more legible. 

LGTM! I think this issue is holding up another [PR](https://github.com/ProjectPythia/pythia-foundations/pull/452) and plenty of other book dev work. Thanks again!

2024-03-25 15:30 UTC, ktyle commented
@erogluorhan and I are meeting to chat at 11AM CDT today (@jukent feel free to join as well!), but I agree that we're on the right track and it will be great to get this merged soon since it will resolve a lot of existing issues. Some things I notice, cookbook-related at least, include:

1. Some cookbooks have Jupyter notebooks whose output does not properly fit in the main (center) panel. In the cases I've tested so far, they have all involved Holoviz/Bokeh-based visualizations.
2. At least on my MacBook Air, the left and right panels are too wide, yet the text does not fully occupy the panel.

2024-03-27 19:13 UTC, erogluorhan commented on .github/workflows/ci.yaml
> +      uses: styfle/cancel-workflow-action@0.12.0
No worries! FYI: The theme update is working now, and its proper functioning (with a few non-vital issues) has been confirmed through tests by a few team members. It is a bit time sensitive before our upcoming community event; hence, I'd like to get it merged and go forward to be used by our portal. 

I've created a new issue though to address this suggestion.

Thanks very much for all your help and review!

2024-03-27 19:13 UTC, merged

2024-03-30 18:06 UTC, erogluorhan commented
Hey @agoose77 please see this [discussion about the theme update](https://github.com/ProjectPythia/projectpythia.github.io/discussions/420). Thanks for everything!